// Auto-generated by scripts/process-photos.ts — do not edit manually.
// Run `just photos <source-dir>` to regenerate.
import type { PhotoManifest } from "./types";

export const manifest: PhotoManifest = {
  "collections": {
    "176": {
      "title": "ART 176",
      "slug": "176",
      "path": "176",
      "blurb": "An intro to digital photography class I took at UW Madison. My section was taught by Jami Balicki <3",
      "blurbHtml": "<p>An intro to digital photography class I took at UW Madison. My section was taught by <a href=\"https://www.instagram.com/jblici_photography/\">Jami Balicki</a> &lt;3</p>\n",
      "sortOrder": 0,
      "children": [
        "176/pa3",
        "176/pa5"
      ],
      "photos": [],
      "parent": null
    },
    "176/pa3": {
      "title": "PA3",
      "slug": "pa3",
      "path": "176/pa3",
      "blurb": "Assignment where we were instructed to experiment with street photography.\nApproaching random people and asking to take their picture pushed me out of my comfort zone, but it was really fun and I love some of these photos!",
      "blurbHtml": "<p>Assignment where we were instructed to experiment with street photography.\nApproaching random people and asking to take their picture pushed me out of my comfort zone, but it was really fun and I love some of these photos!</p>\n",
      "cover": "176/pa3/01",
      "license": "CC BY-NC-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
      "sortOrder": 0,
      "children": [],
      "photos": [
        "176/pa3/01",
        "176/pa3/02",
        "176/pa3/03",
        "176/pa3/04",
        "176/pa3/05",
        "176/pa3/06",
        "176/pa3/07",
        "176/pa3/08",
        "176/pa3/09",
        "176/pa3/10",
        "176/pa3/11",
        "176/pa3/12"
      ],
      "parent": "176"
    },
    "176/pa5": {
      "title": "PA5",
      "slug": "pa5",
      "path": "176/pa5",
      "blurb": "Assignment about exploring light and shadow.",
      "blurbHtml": "<p>Assignment about exploring light and shadow.</p>\n",
      "cover": "176/pa5/01",
      "license": "CC BY-NC-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
      "sortOrder": 0,
      "children": [],
      "photos": [
        "176/pa5/01",
        "176/pa5/02",
        "176/pa5/03",
        "176/pa5/04",
        "176/pa5/05",
        "176/pa5/06",
        "176/pa5/07",
        "176/pa5/08"
      ],
      "parent": "176"
    }
  },
  "photos": {
    "176/pa3/01": {
      "file": "01",
      "path": "176/pa3/01",
      "collection": "176/pa3",
      "title": "",
      "alt": "",
      "aspectRatio": 0.764230498945889,
      "width": 2175,
      "height": 2846,
      "placeholder": "data:image/webp;base64,UklGRg4BAABXRUJQVlA4IAIBAAAwBwCdASogACoAPzmCu1OvKCYisBqqqeAnCWUAzrWz5UtLz762c7cCGGupwmOIPH4jBddy5ShOFUxXZ2BScswhbwAA/f7MIR7uIwWkRGOuDhg2VwHvZNwg/ul54jsE57WehUCmCpeU2n4PbWF0Gmi/StWqRzBYeD22pp8PNarwiMA2+RH6KtkTsyaH0CRgwnAzE0K1wRspOw8ajFEaJj3uYrP/uqSgEehXV7RtR8uSoKOZYqAJDhkq4I1aARsYstS01qs9dUV65DlJV2y3dkGWsbGG6f5UBOBuNTUXieSuTHSbXxS9Qu3Bi96UGu/F/mfICQOzEDJtFpv7NXcHeaygAAA=",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "18.0-55.0 mm f/3.5-5.6",
        "focalLength": "18mm",
        "aperture": "f/4",
        "shutterSpeed": "1/400",
        "iso": 320
      },
      "sizes": {
        "full": {
          "width": 2175,
          "height": 2846,
          "url": "/photos/176/pa3/01/full.webp",
          "bytes": 694848
        },
        "md": {
          "width": 917,
          "height": 1200,
          "url": "/photos/176/pa3/01/1200.webp",
          "bytes": 172172
        },
        "sm": {
          "width": 489,
          "height": 640,
          "url": "/photos/176/pa3/01/640.webp",
          "bytes": 58890
        }
      }
    },
    "176/pa3/02": {
      "file": "02",
      "path": "176/pa3/02",
      "collection": "176/pa3",
      "title": "",
      "alt": "",
      "aspectRatio": 1.45377990430622,
      "width": 7596,
      "height": 5225,
      "placeholder": "data:image/webp;base64,UklGRsoAAABXRUJQVlA4IL4AAACQBQCdASogABYAPzmGuVOvKSWisAgB4CcJZQC4PiAAJ/n4EsOgREjTtrpmUc/Im9ljCZtNoADNcndpHU0PICxMQKo/Gx6Y1aP42fQiGDYxey5tGV/j6lfkrtcGTID1aOsB/ndF14h/R98N+RmODdaRT8fb7HlGHzHhytDPlYoLXwKq9tZvwdu5L77lahW0twY0Mcj8rBLlHN+G5grewcuQRx2olpSahv8hjkyrbbBEZ34giHPwMo4ZwwBSwAAA",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "Nikon AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        "focalLength": "18mm",
        "aperture": "f/4",
        "shutterSpeed": "1/400",
        "iso": 320
      },
      "sizes": {
        "full": {
          "width": 7596,
          "height": 5225,
          "url": "/photos/176/pa3/02/full.webp",
          "bytes": 2146102
        },
        "md": {
          "width": 1200,
          "height": 825,
          "url": "/photos/176/pa3/02/1200.webp",
          "bytes": 125564
        },
        "sm": {
          "width": 640,
          "height": 440,
          "url": "/photos/176/pa3/02/640.webp",
          "bytes": 50836
        }
      }
    },
    "176/pa3/03": {
      "file": "03",
      "path": "176/pa3/03",
      "collection": "176/pa3",
      "title": "",
      "alt": "",
      "aspectRatio": 1,
      "width": 5187,
      "height": 5187,
      "placeholder": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAAAQBQCdASogACAAPzmOu1gvKaWjqAqp4CcJZQDM0BF+/tywqyavh5VrG0Q2ZgWdtoogAP6+WcKnAZjS/sDPOxx3s37BMVH3cG8CuxRCOcgBG6AC9B/4S0sJE5E0qQd3vRYpaemNRhcSOCFjw6FgkPI/MDjdeZcLdMRmGnmf6tYkDWMyD4dXDH+LKFRC9IdymKhyNB16gAA=",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "Nikon AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        "focalLength": "18mm",
        "aperture": "f/4",
        "shutterSpeed": "1/400",
        "iso": 500
      },
      "sizes": {
        "full": {
          "width": 5187,
          "height": 5187,
          "url": "/photos/176/pa3/03/full.webp",
          "bytes": 1708148
        },
        "md": {
          "width": 1200,
          "height": 1200,
          "url": "/photos/176/pa3/03/1200.webp",
          "bytes": 171876
        },
        "sm": {
          "width": 640,
          "height": 640,
          "url": "/photos/176/pa3/03/640.webp",
          "bytes": 60112
        }
      }
    },
    "176/pa3/04": {
      "file": "04",
      "path": "176/pa3/04",
      "collection": "176/pa3",
      "title": "",
      "alt": "",
      "aspectRatio": 1,
      "width": 5380,
      "height": 5380,
      "placeholder": "data:image/webp;base64,UklGRvwAAABXRUJQVlA4IPAAAADwBQCdASogACAAPzmEvVcvJ6YjsBgIAeAnCWMAwPzmuH65Gvh31sigdSrEsKhzTn+uJEorUJAWAAD+72rOo1sa14Tol9OFsCY3iV0wSvHm3FUDBbrm2tusGvUb1NPaCbe3jZ8KRE8gRc5GYokYkqScZBTC4dl783tJnEl6J//fH7Oi0TYCPMrWaHEqCpMuHGjTO/03aM/LlpGSbaYVUIHcRqbVhw5sU2rOixIm64KEtA/Dt9eLQYU9jxSkOMPXwib7Hr/IFKqB4miJcBgFNb9A/vhzAUTbmM//mmAjt/+RkX4q0enx6mmGxGEJxlwAAAA=",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "Nikon AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        "focalLength": "26mm",
        "aperture": "f/4.2",
        "shutterSpeed": "1/4000",
        "iso": 500
      },
      "sizes": {
        "full": {
          "width": 5380,
          "height": 5380,
          "url": "/photos/176/pa3/04/full.webp",
          "bytes": 1571690
        },
        "md": {
          "width": 1200,
          "height": 1200,
          "url": "/photos/176/pa3/04/1200.webp",
          "bytes": 112546
        },
        "sm": {
          "width": 640,
          "height": 640,
          "url": "/photos/176/pa3/04/640.webp",
          "bytes": 47098
        }
      }
    },
    "176/pa3/05": {
      "file": "05",
      "path": "176/pa3/05",
      "collection": "176/pa3",
      "title": "",
      "alt": "",
      "aspectRatio": 1.5056179775280898,
      "width": 8576,
      "height": 5696,
      "placeholder": "data:image/webp;base64,UklGRtYAAABXRUJQVlA4IMoAAADQBQCdASogABUAPzmOwVcvKaejqAqp4CcJYwDI1mwJW5JVAJwRlJ2zHCUDW4yA9rsu5a07iGQAAPlNWXKoH9goqe4ozghloDz3EdgylBnXEZqo36HtooTGSm+u58IABwbVjEuDO9W0MBf6cZZ6jUD7r5LKO9ybGwZsEa5T6Kt/QTcSYFPF4rxFZN72KDR5uOTPjdmEogJK9UYlSj3VeBbsmppJ+GDciF9vzr+LglORMUoLrFgPM08YqRY0N0dDOSNb7PG7kj4IhQAA",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "Nikon AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        "focalLength": "26mm",
        "aperture": "f/4.2",
        "shutterSpeed": "1/4000",
        "iso": 500
      },
      "sizes": {
        "full": {
          "width": 8576,
          "height": 5696,
          "url": "/photos/176/pa3/05/full.webp",
          "bytes": 2365678
        },
        "md": {
          "width": 1200,
          "height": 797,
          "url": "/photos/176/pa3/05/1200.webp",
          "bytes": 45638
        },
        "sm": {
          "width": 640,
          "height": 425,
          "url": "/photos/176/pa3/05/640.webp",
          "bytes": 19892
        }
      }
    },
    "176/pa3/06": {
      "file": "06",
      "path": "176/pa3/06",
      "collection": "176/pa3",
      "title": "",
      "alt": "",
      "aspectRatio": 1.0572331460674158,
      "width": 6022,
      "height": 5696,
      "placeholder": "data:image/webp;base64,UklGRugAAABXRUJQVlA4INwAAAAQBgCdASogAB4APyV8slOuJ6Sit/qoAcAkiWMAxvuoAKDfq5l+ZpoqvREAeg0lRGkFvkyGabgYH+gA/q98ZD88+Ym2mBNvGIOXu210AmvVdfz3L5Qc1qXxxmJq7OAnqh/omj4n8wavTtorvZavGJHJFyGfBfQNUeVLpdTWuauzvRfVgSdOJG73uudmv0OwIpWXhYz/aBHYzzc2pVN7cFnV22e3271HhrPohH5m9JqoybRLR4tJzhNMGkeecg8+jdnZ0KcQZPPltgUKj4Av55OMMUB4WYlZjg0hV5QA",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "Nikon AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        "focalLength": "18mm",
        "aperture": "f/4",
        "shutterSpeed": "1/1250",
        "iso": 200
      },
      "sizes": {
        "full": {
          "width": 6022,
          "height": 5696,
          "url": "/photos/176/pa3/06/full.webp",
          "bytes": 2167788
        },
        "md": {
          "width": 1200,
          "height": 1135,
          "url": "/photos/176/pa3/06/1200.webp",
          "bytes": 193118
        },
        "sm": {
          "width": 640,
          "height": 605,
          "url": "/photos/176/pa3/06/640.webp",
          "bytes": 75346
        }
      }
    },
    "176/pa3/07": {
      "file": "07",
      "path": "176/pa3/07",
      "collection": "176/pa3",
      "title": "",
      "alt": "",
      "aspectRatio": 1.505607476635514,
      "width": 8055,
      "height": 5350,
      "placeholder": "data:image/webp;base64,UklGRsAAAABXRUJQVlA4ILQAAADQBACdASogABUAPzmKtlOvKaSisBgMAeAnCUAZGoWjqH7V8sVYGXHFBFQhiQ/BhAD+GZAspqVglW4kSp15lXYfC3wH1SvWBp0DhGnY8qJ1idU5KepQhdy3NcMpi3Akf+6mYyDsJJ+AMwnpsG6Y72Z6EanWmFe6EFIIhkkg5RQpkNfl5pWDh0ktgawFCyns7ye89th10/VJEIyk8QEanlnl6ZrhJN3abnQRcPMv4k2YptwIAAA=",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "Nikon AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        "focalLength": "26mm",
        "aperture": "f/4.2",
        "shutterSpeed": "1/1250",
        "iso": 200
      },
      "sizes": {
        "full": {
          "width": 8055,
          "height": 5350,
          "url": "/photos/176/pa3/07/full.webp",
          "bytes": 1931996
        },
        "md": {
          "width": 1200,
          "height": 797,
          "url": "/photos/176/pa3/07/1200.webp",
          "bytes": 89162
        },
        "sm": {
          "width": 640,
          "height": 425,
          "url": "/photos/176/pa3/07/640.webp",
          "bytes": 39044
        }
      }
    },
    "176/pa3/08": {
      "file": "08",
      "path": "176/pa3/08",
      "collection": "176/pa3",
      "title": "",
      "alt": "",
      "aspectRatio": 1.5056179775280898,
      "width": 8576,
      "height": 5696,
      "placeholder": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAACwBACdASogABUAPzmSv1mvKaYjqAgB4CcJYwC+SFafN8MwjJsa+JOzKWBru4CgAP70KKgUjXXte+oBPA9/1ZZQH+f27nh4x0e4y7mv6iW/RvNmxlDv8K8lJ1AdlLRWDXIlQdU5V7b6SyiM3swQgiM7qr9usARqu7klKvWQ4bFB/bf06b75FamkAAA=",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "Nikon AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        "focalLength": "18mm",
        "aperture": "f/4",
        "shutterSpeed": "1/4000",
        "iso": 320
      },
      "sizes": {
        "full": {
          "width": 8576,
          "height": 5696,
          "url": "/photos/176/pa3/08/full.webp",
          "bytes": 2791624
        },
        "md": {
          "width": 1200,
          "height": 797,
          "url": "/photos/176/pa3/08/1200.webp",
          "bytes": 82934
        },
        "sm": {
          "width": 640,
          "height": 425,
          "url": "/photos/176/pa3/08/640.webp",
          "bytes": 27210
        }
      }
    },
    "176/pa3/09": {
      "file": "09",
      "path": "176/pa3/09",
      "collection": "176/pa3",
      "title": "",
      "alt": "",
      "aspectRatio": 1.5056179775280898,
      "width": 8576,
      "height": 5696,
      "placeholder": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAABwBACdASogABUAPzmGulOvKSWisAgB4CcJYwDBzCnX+pq4G4ZqJcoWHIvDwAD+7IdhEZiCV5Es5vZnBDYBg3ZljO7nwfzc34xHjJ7CFJtCLTXuHaPdLcy9cU8otaJPf0pRTIlWTd/QAA==",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "Nikon AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        "focalLength": "18mm",
        "aperture": "f/4",
        "shutterSpeed": "1/200",
        "iso": 1000
      },
      "sizes": {
        "full": {
          "width": 8576,
          "height": 5696,
          "url": "/photos/176/pa3/09/full.webp",
          "bytes": 3938008
        },
        "md": {
          "width": 1200,
          "height": 797,
          "url": "/photos/176/pa3/09/1200.webp",
          "bytes": 172060
        },
        "sm": {
          "width": 640,
          "height": 425,
          "url": "/photos/176/pa3/09/640.webp",
          "bytes": 65230
        }
      }
    },
    "176/pa3/10": {
      "file": "10",
      "path": "176/pa3/10",
      "collection": "176/pa3",
      "title": "",
      "alt": "",
      "aspectRatio": 1,
      "width": 5633,
      "height": 5633,
      "placeholder": "data:image/webp;base64,UklGRvoAAABXRUJQVlA4IO4AAABQBgCdASogACAAPzmKulWvKSWjKA1R4CcJZQDMX6gT4hZSCfXFoWVMGLmTFQX8ZEg4fL5MSCMFWT7IgAD8j+r/a6ohLigd4vnZoMbCMZyKtgDmUIaEMS00nLkBfCFPH4qB5ZdQrjXvQONhojaeCAJGFDO279jxo0P4DtbbigSrCujHVblgQhAYFOmA2zHZetqtxy7Oh+8tMUeanjg8LTw6zNGCL0UOb0QP8RvuREy/q7sd8dnBznNOr7euhLNEeMf6TVYRUvjzAIVBt2cGTDu4nIlKjvoi/i7Bc81Sv/QW7TVjH1uuS0wKaJgKAAAA",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "Nikon AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        "focalLength": "34mm",
        "aperture": "f/5",
        "shutterSpeed": "1/640",
        "iso": 200
      },
      "sizes": {
        "full": {
          "width": 5633,
          "height": 5633,
          "url": "/photos/176/pa3/10/full.webp",
          "bytes": 1233978
        },
        "md": {
          "width": 1200,
          "height": 1200,
          "url": "/photos/176/pa3/10/1200.webp",
          "bytes": 116652
        },
        "sm": {
          "width": 640,
          "height": 640,
          "url": "/photos/176/pa3/10/640.webp",
          "bytes": 49308
        }
      }
    },
    "176/pa3/11": {
      "file": "11",
      "path": "176/pa3/11",
      "collection": "176/pa3",
      "title": "",
      "alt": "",
      "aspectRatio": 0.6397235576923077,
      "width": 2129,
      "height": 3328,
      "placeholder": "data:image/webp;base64,UklGRjQBAABXRUJQVlA4ICgBAAAQCACdASogADIAPzmQvVSvKqajLBqrMeAnCWMAyrt+3e7V/HDLufQ0SibURtnbpG7P717dxWbsdGCqKXKmBERB9dIJDjzyN+8kAP4BVhh5earQazEoo7ccODFsLT1/aNDbcT5yBTyaVGAU3ZOQAe53igwB2DkrGe0Pi4PKGkP16ZvmaYecQZEKNe/na7gZdpHuQTDd/rxj8qsio8xlsrf+7tDPrSES4zaR2Tc5vaQkTATgwMNjGBC3YKgDVidgUkhB+M9exqPE20nNM6Z/7dF/n+Qres7DHJ2BWhwaXsq2j08VA+fI8/oCOKJWaGv4CEA+/LTEGTibWdkxQNv18KgIpq/v6ZmMDTXFAM82y50UmswT7A2pOpOKKzlLVWq7rQWk/BEvEwAAAA==",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "Nikon AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        "focalLength": "48mm",
        "aperture": "f/5.6",
        "shutterSpeed": "1/400",
        "iso": 400
      },
      "sizes": {
        "full": {
          "width": 2129,
          "height": 3328,
          "url": "/photos/176/pa3/11/full.webp",
          "bytes": 350618
        },
        "md": {
          "width": 768,
          "height": 1200,
          "url": "/photos/176/pa3/11/1200.webp",
          "bytes": 84190
        },
        "sm": {
          "width": 409,
          "height": 640,
          "url": "/photos/176/pa3/11/640.webp",
          "bytes": 33276
        }
      }
    },
    "176/pa3/12": {
      "file": "12",
      "path": "176/pa3/12",
      "collection": "176/pa3",
      "title": "12 (bonus)",
      "alt": "",
      "aspectRatio": 1.4030898876404494,
      "width": 7992,
      "height": 5696,
      "placeholder": "data:image/webp;base64,UklGRs4AAABXRUJQVlA4IMIAAADwBACdASogABcAPzmKu1avKSWjsBgIAeAnCWMAAHwfG00GX8pGg2iK+eFISVyf9/gA/txxKeA8azfmJbp+EeDTfJE3xv1yEaGxLDyl4bI3pARvc60tBkMR9E68yF2bHUDdSkCny8IiInNzUcao8jqxYi6h6zrTo+8kYdwN8CABotJTG3D+6dNWJiczVaMXxS6eSVsIEBYaC16mZUcyDi76lAIxin8eweX6zHyRoZaVOEStpSzd4w26MTTF/XoK1kwAAA==",
      "exif": {},
      "sizes": {
        "full": {
          "width": 7992,
          "height": 5696,
          "url": "/photos/176/pa3/12/full.webp",
          "bytes": 2414450
        },
        "md": {
          "width": 1200,
          "height": 855,
          "url": "/photos/176/pa3/12/1200.webp",
          "bytes": 105348
        },
        "sm": {
          "width": 640,
          "height": 456,
          "url": "/photos/176/pa3/12/640.webp",
          "bytes": 39660
        }
      }
    },
    "176/pa5/01": {
      "file": "01",
      "path": "176/pa5/01",
      "collection": "176/pa5",
      "title": "",
      "alt": "",
      "aspectRatio": 1.6968838526912182,
      "width": 2995,
      "height": 1765,
      "placeholder": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAADQBACdASogABMAPzmOvVevKaYjqAqp4CcJbAC06GlhgKOupl4TOWE+5xCmHRYsjAD++FDaWHn8C/EX3Whu6x/Wtgle9vy19L1xgTJK/WH9kDNhwr+JPtp6/PXrBxh3XTM869HWi0o7C6fXJGhgddcdXenf6gqCbtZ2SbbsDXR4Q0rQCFHgAzmIAAA=",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "Nikon AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        "focalLength": "18mm",
        "aperture": "f/5.6",
        "shutterSpeed": "1/80",
        "iso": 1250
      },
      "sizes": {
        "full": {
          "width": 2995,
          "height": 1765,
          "url": "/photos/176/pa5/01/full.webp",
          "bytes": 148916
        },
        "md": {
          "width": 1200,
          "height": 707,
          "url": "/photos/176/pa5/01/1200.webp",
          "bytes": 35218
        },
        "sm": {
          "width": 640,
          "height": 377,
          "url": "/photos/176/pa5/01/640.webp",
          "bytes": 13816
        }
      }
    },
    "176/pa5/02": {
      "file": "02",
      "path": "176/pa5/02",
      "collection": "176/pa5",
      "title": "",
      "alt": "",
      "aspectRatio": 1.5056179775280898,
      "width": 4288,
      "height": 2848,
      "placeholder": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAABwBACdASogABUAPzmGvlavKCajsBgIAeAnCWwAxvQwmWJwkW1soYcGT6qSTAD+7qCwQFm53v4poDUh6gONSDbMS47ZnwpuG/p5yH83yFo+aMQ3AN3cLDfy+zK4jvoAuxmwQ3XM28f9f3az2NgAjecIqnAIDLCtq/qIfFAA",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "Nikon AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        "focalLength": "46mm",
        "aperture": "f/5.6",
        "shutterSpeed": "1/60",
        "iso": 1000
      },
      "sizes": {
        "full": {
          "width": 4288,
          "height": 2848,
          "url": "/photos/176/pa5/02/full.webp",
          "bytes": 316572
        },
        "md": {
          "width": 1200,
          "height": 797,
          "url": "/photos/176/pa5/02/1200.webp",
          "bytes": 37806
        },
        "sm": {
          "width": 640,
          "height": 425,
          "url": "/photos/176/pa5/02/640.webp",
          "bytes": 13276
        }
      }
    },
    "176/pa5/03": {
      "file": "03",
      "path": "176/pa5/03",
      "collection": "176/pa5",
      "title": "",
      "alt": "",
      "aspectRatio": 1.3339185393258426,
      "width": 3799,
      "height": 2848,
      "placeholder": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAACwBACdASogABgAPzmQvlevKaYjqAqp4CcJagDE2DTeBLuCEbvrsXlEChAaY6ZgAP7yolx7hA2cl8ctU1/Y8Yai5jM6aOSXo+VAgepDdavYVgqF2gjjcCFzP68E8GoySpmOkwqSI3rwkjPZAa9cP6fgQAl/Wet5kXPQAA==",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "18.0-55.0 mm f/3.5-5.6",
        "focalLength": "50mm",
        "aperture": "f/5.6",
        "shutterSpeed": "1/60",
        "iso": 1000
      },
      "sizes": {
        "full": {
          "width": 3799,
          "height": 2848,
          "url": "/photos/176/pa5/03/full.webp",
          "bytes": 545950
        },
        "md": {
          "width": 1200,
          "height": 900,
          "url": "/photos/176/pa5/03/1200.webp",
          "bytes": 47784
        },
        "sm": {
          "width": 640,
          "height": 480,
          "url": "/photos/176/pa5/03/640.webp",
          "bytes": 17376
        }
      }
    },
    "176/pa5/04": {
      "file": "04",
      "path": "176/pa5/04",
      "collection": "176/pa5",
      "title": "",
      "alt": "",
      "aspectRatio": 1.242626404494382,
      "width": 3539,
      "height": 2848,
      "placeholder": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAACwBQCdASogABoAPzGAtlOuqCUisAwB0CYJbAC7IExDA1oBiNd68LN4tUBpK6fFQODM7NTKtoAA/ssvxrXOxyBuV0QIt8joEOOHfSLas0uqBNwdqwiMTdegoLN1O6ujIzxpx2IGhskxvpdD21ONW1B624SPjSexFMJ0LeftuayoL8KGdLTT71+M72N+Z70lE0iR7MTlrbMcjwAA",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "Nikon AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        "focalLength": "55mm",
        "aperture": "f/5.6",
        "shutterSpeed": "1/160",
        "iso": 640
      },
      "sizes": {
        "full": {
          "width": 3539,
          "height": 2848,
          "url": "/photos/176/pa5/04/full.webp",
          "bytes": 337602
        },
        "md": {
          "width": 1200,
          "height": 966,
          "url": "/photos/176/pa5/04/1200.webp",
          "bytes": 44372
        },
        "sm": {
          "width": 640,
          "height": 515,
          "url": "/photos/176/pa5/04/640.webp",
          "bytes": 15520
        }
      }
    },
    "176/pa5/05": {
      "file": "05",
      "path": "176/pa5/05",
      "collection": "176/pa5",
      "title": "",
      "alt": "",
      "aspectRatio": 1.5056179775280898,
      "width": 4288,
      "height": 2848,
      "placeholder": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAADwBACdASogABUAPzmQu1WvKqYjMBgIAeAnCWMAAB7+DwNJyFowXKtNmqgH14+I5BAA/s9QHrd4IFyiXgbDSpVQP3NwuF6TGoLfiKu2hNh+tU2eiP2pJY9xnUq1/2T8RgZYvx9qGZd9/gXocg+zxGx59xjMmw5XHrXVT8ifUQAAAA==",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "Nikon AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        "focalLength": "34mm",
        "aperture": "f/5",
        "shutterSpeed": "1.3s",
        "iso": 6400
      },
      "sizes": {
        "full": {
          "width": 4288,
          "height": 2848,
          "url": "/photos/176/pa5/05/full.webp",
          "bytes": 2636244
        },
        "md": {
          "width": 1200,
          "height": 797,
          "url": "/photos/176/pa5/05/1200.webp",
          "bytes": 60258
        },
        "sm": {
          "width": 640,
          "height": 425,
          "url": "/photos/176/pa5/05/640.webp",
          "bytes": 15330
        }
      }
    },
    "176/pa5/06": {
      "file": "06",
      "path": "176/pa5/06",
      "collection": "176/pa5",
      "title": "",
      "alt": "",
      "aspectRatio": 1.468092954629288,
      "width": 3980,
      "height": 2711,
      "placeholder": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAADwBACdASogABYAPzmOuVavKaUjqA1R4CcJYwCw7A9K9eBik6+9EMTKbHjpeWDFhfAA+eqRQliUCY9FCjLqliq67/rHvBe7UxGZ7dniJ6gCJzQuHYZ2Wxen/IUYkWYczT5fTHSPN+7dQkBtGCF0MXb7ZxPq5+qodvcM0qcMynqrxrCs1u1WwL1LHElSzrIBKSAAAA==",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "Nikon AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        "focalLength": "18mm",
        "aperture": "f/4.5",
        "shutterSpeed": "1/4",
        "iso": 2000
      },
      "sizes": {
        "full": {
          "width": 3980,
          "height": 2711,
          "url": "/photos/176/pa5/06/full.webp",
          "bytes": 255504
        },
        "md": {
          "width": 1200,
          "height": 817,
          "url": "/photos/176/pa5/06/1200.webp",
          "bytes": 37758
        },
        "sm": {
          "width": 640,
          "height": 436,
          "url": "/photos/176/pa5/06/640.webp",
          "bytes": 15850
        }
      }
    },
    "176/pa5/07": {
      "file": "07",
      "path": "176/pa5/07",
      "collection": "176/pa5",
      "title": "",
      "alt": "",
      "aspectRatio": 1.5246742992499014,
      "width": 3862,
      "height": 2533,
      "placeholder": "data:image/webp;base64,UklGRtIAAABXRUJQVlA4IMYAAAAQBgCdASogABUAPzmKulYvKSWjsBgIAeAnCWwAnTLevPmgACc15pFhwNbfMsPSATDyf7oYPAUwXwAA/p1UPEphV3dd1GY9SfdUGCiHfN5UwSpl16E1Orqd/gb18vwHpRwElReSAyfoyuFkyXr9kKtmhANojmLaChr+9j0GrfAofOy3PVBsMQek9XlJcXm2MivlpuG9t3NBwUr9GCNXfTP+UIsHOd1pCaX/9FcKKZWQB9ldGJEBx1wRH+lpb3voIRnEN8gAAAA=",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "Nikon AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        "focalLength": "26mm",
        "aperture": "f/4.2",
        "shutterSpeed": "1/2500",
        "iso": 250
      },
      "sizes": {
        "full": {
          "width": 3862,
          "height": 2533,
          "url": "/photos/176/pa5/07/full.webp",
          "bytes": 1067616
        },
        "md": {
          "width": 1200,
          "height": 787,
          "url": "/photos/176/pa5/07/1200.webp",
          "bytes": 223544
        },
        "sm": {
          "width": 640,
          "height": 420,
          "url": "/photos/176/pa5/07/640.webp",
          "bytes": 89710
        }
      }
    },
    "176/pa5/08": {
      "file": "08",
      "path": "176/pa5/08",
      "collection": "176/pa5",
      "title": "",
      "alt": "",
      "aspectRatio": 1.3016151685393258,
      "width": 3707,
      "height": 2848,
      "placeholder": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAAAQBQCdASogABkAPzmOuVcvKaUjqA1R4CcJQBUeiLjt3btt4wZOzGbzHEwtbw0OgzoAAP7P2R72ZJOQZp6Z9k5GUOWuygZF0MITEhOui1YVGDKpUklLuAdV6l1pLhusM/DH892lYTtZHrsALhAn+PldrMJ4OloW/O0WXNXFGm914AkWbDcIuuvxLrMyLdWGIJ0jVJEr7N5pdTq9n8AAAA==",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "Nikon AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        "focalLength": "40mm",
        "aperture": "f/5.3",
        "shutterSpeed": "1/1250",
        "iso": 250
      },
      "sizes": {
        "full": {
          "width": 3707,
          "height": 2848,
          "url": "/photos/176/pa5/08/full.webp",
          "bytes": 729520
        },
        "md": {
          "width": 1200,
          "height": 922,
          "url": "/photos/176/pa5/08/1200.webp",
          "bytes": 81630
        },
        "sm": {
          "width": 640,
          "height": 492,
          "url": "/photos/176/pa5/08/640.webp",
          "bytes": 28658
        }
      }
    }
  },
  "totalBytes": 29352852
};
