// Auto-generated by scripts/process-photos.ts — do not edit manually.
// Run `just photos <source-dir>` to regenerate.
import type { PhotoManifest } from "./types";

export const manifest: PhotoManifest = {
  "collections": {
    "176": {
      "title": "ART 176",
      "slug": "176",
      "path": "176",
      "blurb": "An intro to digital photography class I took at UW Madison.\nSome of the photos I'm really proud of aren't included here, ask to see them in person!\nMy section was taught by Jami Balicki <3",
      "blurbHtml": "<p>An intro to digital photography class I took at UW Madison.\nSome of the photos I&#39;m really proud of aren&#39;t included here, ask to see them in person!\nMy section was taught by <a href=\"https://www.instagram.com/jblici_photography/\">Jami Balicki</a> &lt;3</p>\n",
      "covers": [
        "176/pa2/05",
        "176/pa5/01",
        "176/pa3/01"
      ],
      "sortOrder": 0,
      "children": [
        "176/pa2",
        "176/pa3",
        "176/pa5"
      ],
      "photos": [],
      "parent": null
    },
    "176/pa2": {
      "title": "PA2",
      "slug": "pa2",
      "path": "176/pa2",
      "blurb": "Learning how to use a camera!\n\nTook pictures while walking around and at a protest.",
      "blurbHtml": "<p>Learning how to use a camera!\n<br/>\nTook pictures while walking around and at a protest.</p>\n",
      "covers": [
        "176/pa2/05"
      ],
      "license": "CC BY-NC-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
      "sortOrder": 0,
      "children": [],
      "photos": [
        "176/pa2/01",
        "176/pa2/02",
        "176/pa2/03",
        "176/pa2/04",
        "176/pa2/05",
        "176/pa2/06"
      ],
      "parent": "176"
    },
    "176/pa3": {
      "title": "PA3",
      "slug": "pa3",
      "path": "176/pa3",
      "blurb": "Assignment where we were instructed to experiment with street photography.\nApproaching random people and asking to take their picture pushed me out of my comfort zone, but it was really fun and I love some of these photos!",
      "blurbHtml": "<p>Assignment where we were instructed to experiment with street photography.\nApproaching random people and asking to take their picture pushed me out of my comfort zone, but it was really fun and I love some of these photos!</p>\n",
      "covers": [
        "176/pa3/01"
      ],
      "license": "CC BY-NC-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
      "sortOrder": 0,
      "children": [],
      "photos": [
        "176/pa3/01",
        "176/pa3/02",
        "176/pa3/03",
        "176/pa3/04",
        "176/pa3/05",
        "176/pa3/06",
        "176/pa3/07",
        "176/pa3/08",
        "176/pa3/09",
        "176/pa3/10",
        "176/pa3/11",
        "176/pa3/12"
      ],
      "parent": "176"
    },
    "176/pa5": {
      "title": "PA5",
      "slug": "pa5",
      "path": "176/pa5",
      "blurb": "Assignment about exploring light and shadow.",
      "blurbHtml": "<p>Assignment about exploring light and shadow.</p>\n",
      "covers": [
        "176/pa5/01"
      ],
      "license": "CC BY-NC-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
      "sortOrder": 0,
      "children": [],
      "photos": [
        "176/pa5/01",
        "176/pa5/02",
        "176/pa5/03",
        "176/pa5/04",
        "176/pa5/05",
        "176/pa5/06",
        "176/pa5/07",
        "176/pa5/08"
      ],
      "parent": "176"
    }
  },
  "photos": {
    "176/pa3/01": {
      "file": "01",
      "path": "176/pa3/01",
      "collection": "176/pa3",
      "title": "",
      "alt": "",
      "aspectRatio": 0.764230498945889,
      "width": 2175,
      "height": 2846,
      "placeholder": "data:image/webp;base64,UklGRg4BAABXRUJQVlA4IAIBAAAwBwCdASogACoAPzmCu1OvKCYisBqqqeAnCWUAzrWz5UtLz762c7cCGGupwmOIPH4jBddy5ShOFUxXZ2BScswhbwAA/f7MIR7uIwWkRGOuDhg2VwHvZNwg/ul54jsE57WehUCmCpeU2n4PbWF0Gmi/StWqRzBYeD22pp8PNarwiMA2+RH6KtkTsyaH0CRgwnAzE0K1wRspOw8ajFEaJj3uYrP/uqSgEehXV7RtR8uSoKOZYqAJDhkq4I1aARsYstS01qs9dUV65DlJV2y3dkGWsbGG6f5UBOBuNTUXieSuTHSbXxS9Qu3Bi96UGu/F/mfICQOzEDJtFpv7NXcHeaygAAA=",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "Nikon AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        "focalLength": "18mm",
        "aperture": "f/4",
        "shutterSpeed": "1/400",
        "iso": 320
      },
      "sizes": {
        "full": {
          "width": 2175,
          "height": 2846,
          "url": "/photos/176/pa3/01/full.avif",
          "bytes": 699898
        },
        "md": {
          "width": 917,
          "height": 1200,
          "url": "/photos/176/pa3/01/1200.avif",
          "bytes": 182280
        },
        "sm": {
          "width": 489,
          "height": 640,
          "url": "/photos/176/pa3/01/640.avif",
          "bytes": 66642
        }
      }
    },
    "176/pa2/06": {
      "file": "06",
      "path": "176/pa2/06",
      "collection": "176/pa2",
      "title": "",
      "alt": "",
      "aspectRatio": 1.5055124540628828,
      "width": 3687,
      "height": 2449,
      "placeholder": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAwBACdASogABUAPzmQu1WvKiYjMBgIAeAnCWcAAI91uZIeEwC3J27sdhAA/u50E5xcLki9R0784qNj36TaW0iJcWTJfQbdZsAAAA==",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "18.0-55.0 mm f/3.5-5.6",
        "focalLength": "55mm",
        "aperture": "f/5.6",
        "shutterSpeed": "1/60",
        "iso": 6400
      },
      "sizes": {
        "full": {
          "width": 3687,
          "height": 2449,
          "url": "/photos/176/pa2/06/full.avif",
          "bytes": 1239061
        },
        "md": {
          "width": 1200,
          "height": 797,
          "url": "/photos/176/pa2/06/1200.avif",
          "bytes": 44753
        },
        "sm": {
          "width": 640,
          "height": 425,
          "url": "/photos/176/pa2/06/640.avif",
          "bytes": 5973
        }
      }
    },
    "176/pa2/02": {
      "file": "02",
      "path": "176/pa2/02",
      "collection": "176/pa2",
      "title": "",
      "alt": "",
      "aspectRatio": 1.5053353658536586,
      "width": 3950,
      "height": 2624,
      "placeholder": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAADQBACdASogABUAPzmEtlOvKCSisAgB4CcJYgDDNBiwItoezXf2nf8GMueN5kb/kAD+PXcEO/ZC/N29Czne1qIuJhb/JVQPr/VEGvLUD2Kbd0j8CrL5vipCOmBqiU6THtElrRiPFTIh2GMxk78dmTqyj0lk+mYl4dQoLtrpTXtAZngR4FA5diSEKEoM0AAA",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "18.0-55.0 mm f/3.5-5.6",
        "focalLength": "55mm",
        "aperture": "f/5.6",
        "shutterSpeed": "1/1000",
        "iso": 100
      },
      "sizes": {
        "full": {
          "width": 3950,
          "height": 2624,
          "url": "/photos/176/pa2/02/full.avif",
          "bytes": 402771
        },
        "md": {
          "width": 1200,
          "height": 797,
          "url": "/photos/176/pa2/02/1200.avif",
          "bytes": 113340
        },
        "sm": {
          "width": 640,
          "height": 425,
          "url": "/photos/176/pa2/02/640.avif",
          "bytes": 51111
        }
      }
    },
    "176/pa2/04": {
      "file": "04",
      "path": "176/pa2/04",
      "collection": "176/pa2",
      "title": "",
      "alt": "",
      "aspectRatio": 1.5054704595185995,
      "width": 4128,
      "height": 2742,
      "placeholder": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAwCdASogABUAPzmOwFevKaapqAqp4CcJZQDE2BBWxLozbW1i7G4AAPnjeckyiCI0UvebELvBfcn7xENEehmsWhdUT2LtgCX73YQ4ztsW5X+PZAAAAA==",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "18.0-55.0 mm f/3.5-5.6",
        "focalLength": "55mm",
        "aperture": "f/5.6",
        "shutterSpeed": "1/1000",
        "iso": 100
      },
      "sizes": {
        "full": {
          "width": 4128,
          "height": 2742,
          "url": "/photos/176/pa2/04/full.avif",
          "bytes": 253523
        },
        "md": {
          "width": 1200,
          "height": 797,
          "url": "/photos/176/pa2/04/1200.avif",
          "bytes": 52910
        },
        "sm": {
          "width": 640,
          "height": 425,
          "url": "/photos/176/pa2/04/640.avif",
          "bytes": 23543
        }
      }
    },
    "176/pa2/01": {
      "file": "01",
      "path": "176/pa2/01",
      "collection": "176/pa2",
      "title": "",
      "alt": "",
      "aspectRatio": 1.5057996485061511,
      "width": 4284,
      "height": 2845,
      "placeholder": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAAAQBQCdASogABUAPzmIvVYvKKajsBgIAeAnCUAAELKZvm8DUfRSl4yxjR3b4kYo1B0AAP6gpgDxfHb0utg3s2ZF68rEo/XcoMxW8Ec1CNEwjiRYly9Uvk2DiTzCf0Phgr4r21oK6EU64oOrAHuTEzkUq2/4RTSi+3uS62Ixswk3vmzIviJ4i6vQimtQagUVEJYmOtggQbkJDAAA",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "18.0-55.0 mm f/3.5-5.6",
        "focalLength": "55mm",
        "aperture": "f/5.6",
        "shutterSpeed": "1/250",
        "iso": 100
      },
      "sizes": {
        "full": {
          "width": 4284,
          "height": 2845,
          "url": "/photos/176/pa2/01/full.avif",
          "bytes": 782973
        },
        "md": {
          "width": 1200,
          "height": 797,
          "url": "/photos/176/pa2/01/1200.avif",
          "bytes": 134326
        },
        "sm": {
          "width": 640,
          "height": 425,
          "url": "/photos/176/pa2/01/640.avif",
          "bytes": 58257
        }
      }
    },
    "176/pa2/05": {
      "file": "05",
      "path": "176/pa2/05",
      "collection": "176/pa2",
      "title": "",
      "alt": "",
      "aspectRatio": 1.5056939501779358,
      "width": 4231,
      "height": 2810,
      "placeholder": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACwAwCdASogABUAPy2At1OuqCWisAwB0CWJZwAANKFAF8r+55UdQAD5nMqOAYxtbszpaSAVxwe9R/HaK3S6UFBeQg1CBAAA",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "18.0-55.0 mm f/3.5-5.6",
        "focalLength": "48mm",
        "aperture": "f/5.6",
        "shutterSpeed": "1/800",
        "iso": 400
      },
      "sizes": {
        "full": {
          "width": 4231,
          "height": 2810,
          "url": "/photos/176/pa2/05/full.avif",
          "bytes": 759022
        },
        "md": {
          "width": 1200,
          "height": 797,
          "url": "/photos/176/pa2/05/1200.avif",
          "bytes": 20541
        },
        "sm": {
          "width": 640,
          "height": 425,
          "url": "/photos/176/pa2/05/640.avif",
          "bytes": 7979
        }
      }
    },
    "176/pa3/11": {
      "file": "11",
      "path": "176/pa3/11",
      "collection": "176/pa3",
      "title": "",
      "alt": "",
      "aspectRatio": 0.6397235576923077,
      "width": 2129,
      "height": 3328,
      "placeholder": "data:image/webp;base64,UklGRjQBAABXRUJQVlA4ICgBAAAQCACdASogADIAPzmQvVSvKqajLBqrMeAnCWMAyrt+3e7V/HDLufQ0SibURtnbpG7P717dxWbsdGCqKXKmBERB9dIJDjzyN+8kAP4BVhh5earQazEoo7ccODFsLT1/aNDbcT5yBTyaVGAU3ZOQAe53igwB2DkrGe0Pi4PKGkP16ZvmaYecQZEKNe/na7gZdpHuQTDd/rxj8qsio8xlsrf+7tDPrSES4zaR2Tc5vaQkTATgwMNjGBC3YKgDVidgUkhB+M9exqPE20nNM6Z/7dF/n+Qres7DHJ2BWhwaXsq2j08VA+fI8/oCOKJWaGv4CEA+/LTEGTibWdkxQNv18KgIpq/v6ZmMDTXFAM82y50UmswT7A2pOpOKKzlLVWq7rQWk/BEvEwAAAA==",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "Nikon AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        "focalLength": "48mm",
        "aperture": "f/5.6",
        "shutterSpeed": "1/400",
        "iso": 400
      },
      "sizes": {
        "full": {
          "width": 2129,
          "height": 3328,
          "url": "/photos/176/pa3/11/full.avif",
          "bytes": 313177
        },
        "md": {
          "width": 768,
          "height": 1200,
          "url": "/photos/176/pa3/11/1200.avif",
          "bytes": 86842
        },
        "sm": {
          "width": 409,
          "height": 640,
          "url": "/photos/176/pa3/11/640.avif",
          "bytes": 36825
        }
      }
    },
    "176/pa5/01": {
      "file": "01",
      "path": "176/pa5/01",
      "collection": "176/pa5",
      "title": "",
      "alt": "",
      "aspectRatio": 1.6968838526912182,
      "width": 2995,
      "height": 1765,
      "placeholder": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAADQBACdASogABMAPzmOvVevKaYjqAqp4CcJbAC06GlhgKOupl4TOWE+5xCmHRYsjAD++FDaWHn8C/EX3Whu6x/Wtgle9vy19L1xgTJK/WH9kDNhwr+JPtp6/PXrBxh3XTM869HWi0o7C6fXJGhgddcdXenf6gqCbtZ2SbbsDXR4Q0rQCFHgAzmIAAA=",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "Nikon AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        "focalLength": "18mm",
        "aperture": "f/5.6",
        "shutterSpeed": "1/80",
        "iso": 1250
      },
      "sizes": {
        "full": {
          "width": 2995,
          "height": 1765,
          "url": "/photos/176/pa5/01/full.avif",
          "bytes": 124768
        },
        "md": {
          "width": 1200,
          "height": 707,
          "url": "/photos/176/pa5/01/1200.avif",
          "bytes": 30365
        },
        "sm": {
          "width": 640,
          "height": 377,
          "url": "/photos/176/pa5/01/640.avif",
          "bytes": 12630
        }
      }
    },
    "176/pa5/04": {
      "file": "04",
      "path": "176/pa5/04",
      "collection": "176/pa5",
      "title": "",
      "alt": "",
      "aspectRatio": 1.242626404494382,
      "width": 3539,
      "height": 2848,
      "placeholder": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAACwBQCdASogABoAPzGAtlOuqCUisAwB0CYJbAC7IExDA1oBiNd68LN4tUBpK6fFQODM7NTKtoAA/ssvxrXOxyBuV0QIt8joEOOHfSLas0uqBNwdqwiMTdegoLN1O6ujIzxpx2IGhskxvpdD21ONW1B624SPjSexFMJ0LeftuayoL8KGdLTT71+M72N+Z70lE0iR7MTlrbMcjwAA",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "Nikon AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        "focalLength": "55mm",
        "aperture": "f/5.6",
        "shutterSpeed": "1/160",
        "iso": 640
      },
      "sizes": {
        "full": {
          "width": 3539,
          "height": 2848,
          "url": "/photos/176/pa5/04/full.avif",
          "bytes": 309776
        },
        "md": {
          "width": 1200,
          "height": 966,
          "url": "/photos/176/pa5/04/1200.avif",
          "bytes": 42254
        },
        "sm": {
          "width": 640,
          "height": 515,
          "url": "/photos/176/pa5/04/640.avif",
          "bytes": 15227
        }
      }
    },
    "176/pa5/03": {
      "file": "03",
      "path": "176/pa5/03",
      "collection": "176/pa5",
      "title": "",
      "alt": "",
      "aspectRatio": 1.3339185393258426,
      "width": 3799,
      "height": 2848,
      "placeholder": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAACwBACdASogABgAPzmQvlevKaYjqAqp4CcJagDE2DTeBLuCEbvrsXlEChAaY6ZgAP7yolx7hA2cl8ctU1/Y8Yai5jM6aOSXo+VAgepDdavYVgqF2gjjcCFzP68E8GoySpmOkwqSI3rwkjPZAa9cP6fgQAl/Wet5kXPQAA==",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "Nikon AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        "focalLength": "50mm",
        "aperture": "f/5.6",
        "shutterSpeed": "1/60",
        "iso": 1000
      },
      "sizes": {
        "full": {
          "width": 3799,
          "height": 2848,
          "url": "/photos/176/pa5/03/full.avif",
          "bytes": 612858
        },
        "md": {
          "width": 1200,
          "height": 900,
          "url": "/photos/176/pa5/03/1200.avif",
          "bytes": 45801
        },
        "sm": {
          "width": 640,
          "height": 480,
          "url": "/photos/176/pa5/03/640.avif",
          "bytes": 17488
        }
      }
    },
    "176/pa5/02": {
      "file": "02",
      "path": "176/pa5/02",
      "collection": "176/pa5",
      "title": "",
      "alt": "",
      "aspectRatio": 1.5056179775280898,
      "width": 4288,
      "height": 2848,
      "placeholder": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAABwBACdASogABUAPzmGvlavKCajsBgIAeAnCWwAxvQwmWJwkW1soYcGT6qSTAD+7qCwQFm53v4poDUh6gONSDbMS47ZnwpuG/p5yH83yFo+aMQ3AN3cLDfy+zK4jvoAuxmwQ3XM28f9f3az2NgAjecIqnAIDLCtq/qIfFAA",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "Nikon AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        "focalLength": "46mm",
        "aperture": "f/5.6",
        "shutterSpeed": "1/60",
        "iso": 1000
      },
      "sizes": {
        "full": {
          "width": 4288,
          "height": 2848,
          "url": "/photos/176/pa5/02/full.avif",
          "bytes": 260983
        },
        "md": {
          "width": 1200,
          "height": 797,
          "url": "/photos/176/pa5/02/1200.avif",
          "bytes": 36980
        },
        "sm": {
          "width": 640,
          "height": 425,
          "url": "/photos/176/pa5/02/640.avif",
          "bytes": 13182
        }
      }
    },
    "176/pa3/03": {
      "file": "03",
      "path": "176/pa3/03",
      "collection": "176/pa3",
      "title": "",
      "alt": "",
      "aspectRatio": 1,
      "width": 5187,
      "height": 5187,
      "placeholder": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAAAQBQCdASogACAAPzmOu1gvKaWjqAqp4CcJZQDM0BF+/tywqyavh5VrG0Q2ZgWdtoogAP6+WcKnAZjS/sDPOxx3s37BMVH3cG8CuxRCOcgBG6AC9B/4S0sJE5E0qQd3vRYpaemNRhcSOCFjw6FgkPI/MDjdeZcLdMRmGnmf6tYkDWMyD4dXDH+LKFRC9IdymKhyNB16gAA=",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "Nikon AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        "focalLength": "18mm",
        "aperture": "f/4",
        "shutterSpeed": "1/400",
        "iso": 500
      },
      "sizes": {
        "full": {
          "width": 5187,
          "height": 5187,
          "url": "/photos/176/pa3/03/full.avif",
          "bytes": 1615280
        },
        "md": {
          "width": 1200,
          "height": 1200,
          "url": "/photos/176/pa3/03/1200.avif",
          "bytes": 191607
        },
        "sm": {
          "width": 640,
          "height": 640,
          "url": "/photos/176/pa3/03/640.avif",
          "bytes": 70211
        }
      }
    },
    "176/pa2/03": {
      "file": "03",
      "path": "176/pa2/03",
      "collection": "176/pa2",
      "title": "",
      "alt": "",
      "aspectRatio": 0.7815205118554761,
      "width": 4153,
      "height": 5314,
      "placeholder": "data:image/webp;base64,UklGRhgBAABXRUJQVlA4IAwBAADwBgCdASogACkAPzmKu1cvKSWjsBVYAeAnCWUAyJssBRVu/Rj+Kfocc1WpOomHoTiXE41kb0KQONSuAb6yecVAAP5Ud3JKbZgMgmeFYqQIew+JMDFnCx38ZZiE4C9Psl0T7FUtTd1PpK8PVoaXWcY5dPQD69ybNsNTOgyVeTBuED30NzEZZjH0NL5CLpdRRRaf1b5tGbxxTQm3z/ZupTszGnbwxpmd634V4P4h+GQJSNNrTvGmr4i1TAITigXrcud3aXXWYeGKhe1MxMYCZ37ZO73vGNeohfEazYI5fQBZEj9RNWmWjw3JwtvZ/bxLIkmUZgu3l4ZdSvYac8Hv9qHZECy8uVOEPTIIDAAA",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "18.0-55.0 mm f/3.5-5.6",
        "focalLength": "55mm",
        "aperture": "f/5.6",
        "shutterSpeed": "1/100",
        "iso": 100
      },
      "sizes": {
        "full": {
          "width": 4153,
          "height": 5314,
          "url": "/photos/176/pa2/03/full.avif",
          "bytes": 620909
        },
        "md": {
          "width": 938,
          "height": 1200,
          "url": "/photos/176/pa2/03/1200.avif",
          "bytes": 99463
        },
        "sm": {
          "width": 500,
          "height": 640,
          "url": "/photos/176/pa2/03/640.avif",
          "bytes": 46222
        }
      }
    },
    "176/pa3/04": {
      "file": "04",
      "path": "176/pa3/04",
      "collection": "176/pa3",
      "title": "",
      "alt": "",
      "aspectRatio": 1,
      "width": 5380,
      "height": 5380,
      "placeholder": "data:image/webp;base64,UklGRvwAAABXRUJQVlA4IPAAAADwBQCdASogACAAPzmEvVcvJ6YjsBgIAeAnCWMAwPzmuH65Gvh31sigdSrEsKhzTn+uJEorUJAWAAD+72rOo1sa14Tol9OFsCY3iV0wSvHm3FUDBbrm2tusGvUb1NPaCbe3jZ8KRE8gRc5GYokYkqScZBTC4dl783tJnEl6J//fH7Oi0TYCPMrWaHEqCpMuHGjTO/03aM/LlpGSbaYVUIHcRqbVhw5sU2rOixIm64KEtA/Dt9eLQYU9jxSkOMPXwib7Hr/IFKqB4miJcBgFNb9A/vhzAUTbmM//mmAjt/+RkX4q0enx6mmGxGEJxlwAAAA=",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "Nikon AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        "focalLength": "26mm",
        "aperture": "f/4.2",
        "shutterSpeed": "1/4000",
        "iso": 500
      },
      "sizes": {
        "full": {
          "width": 5380,
          "height": 5380,
          "url": "/photos/176/pa3/04/full.avif",
          "bytes": 1466562
        },
        "md": {
          "width": 1200,
          "height": 1200,
          "url": "/photos/176/pa3/04/1200.avif",
          "bytes": 116849
        },
        "sm": {
          "width": 640,
          "height": 640,
          "url": "/photos/176/pa3/04/640.avif",
          "bytes": 50847
        }
      }
    },
    "176/pa5/05": {
      "file": "05",
      "path": "176/pa5/05",
      "collection": "176/pa5",
      "title": "",
      "alt": "",
      "aspectRatio": 1.5056179775280898,
      "width": 4288,
      "height": 2848,
      "placeholder": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAADwBACdASogABUAPzmQu1WvKqYjMBgIAeAnCWMAAB7+DwNJyFowXKtNmqgH14+I5BAA/s9QHrd4IFyiXgbDSpVQP3NwuF6TGoLfiKu2hNh+tU2eiP2pJY9xnUq1/2T8RgZYvx9qGZd9/gXocg+zxGx59xjMmw5XHrXVT8ifUQAAAA==",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "Nikon AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        "focalLength": "34mm",
        "aperture": "f/5",
        "shutterSpeed": "1.3s",
        "iso": 6400
      },
      "sizes": {
        "full": {
          "width": 4288,
          "height": 2848,
          "url": "/photos/176/pa5/05/full.avif",
          "bytes": 2688797
        },
        "md": {
          "width": 1200,
          "height": 797,
          "url": "/photos/176/pa5/05/1200.avif",
          "bytes": 61149
        },
        "sm": {
          "width": 640,
          "height": 425,
          "url": "/photos/176/pa5/05/640.avif",
          "bytes": 12365
        }
      }
    },
    "176/pa5/06": {
      "file": "06",
      "path": "176/pa5/06",
      "collection": "176/pa5",
      "title": "",
      "alt": "",
      "aspectRatio": 1.468092954629288,
      "width": 3980,
      "height": 2711,
      "placeholder": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAADwBACdASogABYAPzmOuVavKaUjqA1R4CcJYwCw7A9K9eBik6+9EMTKbHjpeWDFhfAA+eqRQliUCY9FCjLqliq67/rHvBe7UxGZ7dniJ6gCJzQuHYZ2Wxen/IUYkWYczT5fTHSPN+7dQkBtGCF0MXb7ZxPq5+qodvcM0qcMynqrxrCs1u1WwL1LHElSzrIBKSAAAA==",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "Nikon AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        "focalLength": "18mm",
        "aperture": "f/4.5",
        "shutterSpeed": "1/4",
        "iso": 2000
      },
      "sizes": {
        "full": {
          "width": 3980,
          "height": 2711,
          "url": "/photos/176/pa5/06/full.avif",
          "bytes": 181660
        },
        "md": {
          "width": 1200,
          "height": 817,
          "url": "/photos/176/pa5/06/1200.avif",
          "bytes": 34028
        },
        "sm": {
          "width": 640,
          "height": 436,
          "url": "/photos/176/pa5/06/640.avif",
          "bytes": 15672
        }
      }
    },
    "176/pa3/10": {
      "file": "10",
      "path": "176/pa3/10",
      "collection": "176/pa3",
      "title": "",
      "alt": "",
      "aspectRatio": 1,
      "width": 5633,
      "height": 5633,
      "placeholder": "data:image/webp;base64,UklGRvoAAABXRUJQVlA4IO4AAABQBgCdASogACAAPzmKulWvKSWjKA1R4CcJZQDMX6gT4hZSCfXFoWVMGLmTFQX8ZEg4fL5MSCMFWT7IgAD8j+r/a6ohLigd4vnZoMbCMZyKtgDmUIaEMS00nLkBfCFPH4qB5ZdQrjXvQONhojaeCAJGFDO279jxo0P4DtbbigSrCujHVblgQhAYFOmA2zHZetqtxy7Oh+8tMUeanjg8LTw6zNGCL0UOb0QP8RvuREy/q7sd8dnBznNOr7euhLNEeMf6TVYRUvjzAIVBt2cGTDu4nIlKjvoi/i7Bc81Sv/QW7TVjH1uuS0wKaJgKAAAA",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "Nikon AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        "focalLength": "34mm",
        "aperture": "f/5",
        "shutterSpeed": "1/640",
        "iso": 200
      },
      "sizes": {
        "full": {
          "width": 5633,
          "height": 5633,
          "url": "/photos/176/pa3/10/full.avif",
          "bytes": 1110906
        },
        "md": {
          "width": 1200,
          "height": 1200,
          "url": "/photos/176/pa3/10/1200.avif",
          "bytes": 116268
        },
        "sm": {
          "width": 640,
          "height": 640,
          "url": "/photos/176/pa3/10/640.avif",
          "bytes": 52574
        }
      }
    },
    "176/pa3/06": {
      "file": "06",
      "path": "176/pa3/06",
      "collection": "176/pa3",
      "title": "",
      "alt": "",
      "aspectRatio": 1.0572331460674158,
      "width": 6022,
      "height": 5696,
      "placeholder": "data:image/webp;base64,UklGRugAAABXRUJQVlA4INwAAAAQBgCdASogAB4APyV8slOuJ6Sit/qoAcAkiWMAxvuoAKDfq5l+ZpoqvREAeg0lRGkFvkyGabgYH+gA/q98ZD88+Ym2mBNvGIOXu210AmvVdfz3L5Qc1qXxxmJq7OAnqh/omj4n8wavTtorvZavGJHJFyGfBfQNUeVLpdTWuauzvRfVgSdOJG73uudmv0OwIpWXhYz/aBHYzzc2pVN7cFnV22e3271HhrPohH5m9JqoybRLR4tJzhNMGkeecg8+jdnZ0KcQZPPltgUKj4Av55OMMUB4WYlZjg0hV5QA",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "Nikon AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        "focalLength": "18mm",
        "aperture": "f/4",
        "shutterSpeed": "1/1250",
        "iso": 200
      },
      "sizes": {
        "full": {
          "width": 6022,
          "height": 5696,
          "url": "/photos/176/pa3/06/full.avif",
          "bytes": 1948189
        },
        "md": {
          "width": 1200,
          "height": 1135,
          "url": "/photos/176/pa3/06/1200.avif",
          "bytes": 218297
        },
        "sm": {
          "width": 640,
          "height": 605,
          "url": "/photos/176/pa3/06/640.avif",
          "bytes": 88182
        }
      }
    },
    "176/pa5/07": {
      "file": "07",
      "path": "176/pa5/07",
      "collection": "176/pa5",
      "title": "",
      "alt": "",
      "aspectRatio": 1.5246742992499014,
      "width": 3862,
      "height": 2533,
      "placeholder": "data:image/webp;base64,UklGRtIAAABXRUJQVlA4IMYAAAAQBgCdASogABUAPzmKulYvKSWjsBgIAeAnCWwAnTLevPmgACc15pFhwNbfMsPSATDyf7oYPAUwXwAA/p1UPEphV3dd1GY9SfdUGCiHfN5UwSpl16E1Orqd/gb18vwHpRwElReSAyfoyuFkyXr9kKtmhANojmLaChr+9j0GrfAofOy3PVBsMQek9XlJcXm2MivlpuG9t3NBwUr9GCNXfTP+UIsHOd1pCaX/9FcKKZWQB9ldGJEBx1wRH+lpb3voIRnEN8gAAAA=",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "Nikon AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        "focalLength": "26mm",
        "aperture": "f/4.2",
        "shutterSpeed": "1/2500",
        "iso": 250
      },
      "sizes": {
        "full": {
          "width": 3862,
          "height": 2533,
          "url": "/photos/176/pa5/07/full.avif",
          "bytes": 1092848
        },
        "md": {
          "width": 1200,
          "height": 787,
          "url": "/photos/176/pa5/07/1200.avif",
          "bytes": 272135
        },
        "sm": {
          "width": 640,
          "height": 420,
          "url": "/photos/176/pa5/07/640.avif",
          "bytes": 119972
        }
      }
    },
    "176/pa5/08": {
      "file": "08",
      "path": "176/pa5/08",
      "collection": "176/pa5",
      "title": "",
      "alt": "",
      "aspectRatio": 1.3016151685393258,
      "width": 3707,
      "height": 2848,
      "placeholder": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAAAQBQCdASogABkAPzmOuVcvKaUjqA1R4CcJQBUeiLjt3btt4wZOzGbzHEwtbw0OgzoAAP7P2R72ZJOQZp6Z9k5GUOWuygZF0MITEhOui1YVGDKpUklLuAdV6l1pLhusM/DH892lYTtZHrsALhAn+PldrMJ4OloW/O0WXNXFGm914AkWbDcIuuvxLrMyLdWGIJ0jVJEr7N5pdTq9n8AAAA==",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "Nikon AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        "focalLength": "40mm",
        "aperture": "f/5.3",
        "shutterSpeed": "1/1250",
        "iso": 250
      },
      "sizes": {
        "full": {
          "width": 3707,
          "height": 2848,
          "url": "/photos/176/pa5/08/full.avif",
          "bytes": 737685
        },
        "md": {
          "width": 1200,
          "height": 922,
          "url": "/photos/176/pa5/08/1200.avif",
          "bytes": 84407
        },
        "sm": {
          "width": 640,
          "height": 492,
          "url": "/photos/176/pa5/08/640.avif",
          "bytes": 31010
        }
      }
    },
    "176/pa3/02": {
      "file": "02",
      "path": "176/pa3/02",
      "collection": "176/pa3",
      "title": "",
      "alt": "",
      "aspectRatio": 1.45377990430622,
      "width": 7596,
      "height": 5225,
      "placeholder": "data:image/webp;base64,UklGRsoAAABXRUJQVlA4IL4AAACQBQCdASogABYAPzmGuVOvKSWisAgB4CcJZQC4PiAAJ/n4EsOgREjTtrpmUc/Im9ljCZtNoADNcndpHU0PICxMQKo/Gx6Y1aP42fQiGDYxey5tGV/j6lfkrtcGTID1aOsB/ndF14h/R98N+RmODdaRT8fb7HlGHzHhytDPlYoLXwKq9tZvwdu5L77lahW0twY0Mcj8rBLlHN+G5grewcuQRx2olpSahv8hjkyrbbBEZ34giHPwMo4ZwwBSwAAA",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "Nikon AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        "focalLength": "18mm",
        "aperture": "f/4",
        "shutterSpeed": "1/400",
        "iso": 320
      },
      "sizes": {
        "full": {
          "width": 7596,
          "height": 5225,
          "url": "/photos/176/pa3/02/full.avif",
          "bytes": 1935141
        },
        "md": {
          "width": 1200,
          "height": 825,
          "url": "/photos/176/pa3/02/1200.avif",
          "bytes": 134463
        },
        "sm": {
          "width": 640,
          "height": 440,
          "url": "/photos/176/pa3/02/640.avif",
          "bytes": 57119
        }
      }
    },
    "176/pa3/12": {
      "file": "12",
      "path": "176/pa3/12",
      "collection": "176/pa3",
      "title": "12 (bonus)",
      "alt": "",
      "process": "Digital composite",
      "aspectRatio": 1.4030898876404494,
      "width": 7992,
      "height": 5696,
      "placeholder": "data:image/webp;base64,UklGRs4AAABXRUJQVlA4IMIAAADwBACdASogABcAPzmKu1avKSWjsBgIAeAnCWMAAHwfG00GX8pGg2iK+eFISVyf9/gA/txxKeA8azfmJbp+EeDTfJE3xv1yEaGxLDyl4bI3pARvc60tBkMR9E68yF2bHUDdSkCny8IiInNzUcao8jqxYi6h6zrTo+8kYdwN8CABotJTG3D+6dNWJiczVaMXxS6eSVsIEBYaC16mZUcyDi76lAIxin8eweX6zHyRoZaVOEStpSzd4w26MTTF/XoK1kwAAA==",
      "exif": {},
      "sizes": {
        "full": {
          "width": 7992,
          "height": 5696,
          "url": "/photos/176/pa3/12/full.avif",
          "bytes": 2306713
        },
        "md": {
          "width": 1200,
          "height": 855,
          "url": "/photos/176/pa3/12/1200.avif",
          "bytes": 111089
        },
        "sm": {
          "width": 640,
          "height": 456,
          "url": "/photos/176/pa3/12/640.avif",
          "bytes": 43133
        }
      }
    },
    "176/pa3/07": {
      "file": "07",
      "path": "176/pa3/07",
      "collection": "176/pa3",
      "title": "",
      "alt": "",
      "aspectRatio": 1.505607476635514,
      "width": 8055,
      "height": 5350,
      "placeholder": "data:image/webp;base64,UklGRsAAAABXRUJQVlA4ILQAAADQBACdASogABUAPzmKtlOvKaSisBgMAeAnCUAZGoWjqH7V8sVYGXHFBFQhiQ/BhAD+GZAspqVglW4kSp15lXYfC3wH1SvWBp0DhGnY8qJ1idU5KepQhdy3NcMpi3Akf+6mYyDsJJ+AMwnpsG6Y72Z6EanWmFe6EFIIhkkg5RQpkNfl5pWDh0ktgawFCyns7ye89th10/VJEIyk8QEanlnl6ZrhJN3abnQRcPMv4k2YptwIAAA=",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "Nikon AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        "focalLength": "26mm",
        "aperture": "f/4.2",
        "shutterSpeed": "1/1250",
        "iso": 200
      },
      "sizes": {
        "full": {
          "width": 8055,
          "height": 5350,
          "url": "/photos/176/pa3/07/full.avif",
          "bytes": 1810969
        },
        "md": {
          "width": 1200,
          "height": 797,
          "url": "/photos/176/pa3/07/1200.avif",
          "bytes": 94473
        },
        "sm": {
          "width": 640,
          "height": 425,
          "url": "/photos/176/pa3/07/640.avif",
          "bytes": 43032
        }
      }
    },
    "176/pa3/09": {
      "file": "09",
      "path": "176/pa3/09",
      "collection": "176/pa3",
      "title": "",
      "alt": "",
      "aspectRatio": 1.5056179775280898,
      "width": 8576,
      "height": 5696,
      "placeholder": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAABwBACdASogABUAPzmGulOvKSWisAgB4CcJYwDBzCnX+pq4G4ZqJcoWHIvDwAD+7IdhEZiCV5Es5vZnBDYBg3ZljO7nwfzc34xHjJ7CFJtCLTXuHaPdLcy9cU8otaJPf0pRTIlWTd/QAA==",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "Nikon AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        "focalLength": "18mm",
        "aperture": "f/4",
        "shutterSpeed": "1/200",
        "iso": 1000
      },
      "sizes": {
        "full": {
          "width": 8576,
          "height": 5696,
          "url": "/photos/176/pa3/09/full.avif",
          "bytes": 3706304
        },
        "md": {
          "width": 1200,
          "height": 797,
          "url": "/photos/176/pa3/09/1200.avif",
          "bytes": 211755
        },
        "sm": {
          "width": 640,
          "height": 425,
          "url": "/photos/176/pa3/09/640.avif",
          "bytes": 80682
        }
      }
    },
    "176/pa3/05": {
      "file": "05",
      "path": "176/pa3/05",
      "collection": "176/pa3",
      "title": "",
      "alt": "",
      "aspectRatio": 1.5056179775280898,
      "width": 8576,
      "height": 5696,
      "placeholder": "data:image/webp;base64,UklGRtYAAABXRUJQVlA4IMoAAADQBQCdASogABUAPzmOwVcvKaejqAqp4CcJYwDI1mwJW5JVAJwRlJ2zHCUDW4yA9rsu5a07iGQAAPlNWXKoH9goqe4ozghloDz3EdgylBnXEZqo36HtooTGSm+u58IABwbVjEuDO9W0MBf6cZZ6jUD7r5LKO9ybGwZsEa5T6Kt/QTcSYFPF4rxFZN72KDR5uOTPjdmEogJK9UYlSj3VeBbsmppJ+GDciF9vzr+LglORMUoLrFgPM08YqRY0N0dDOSNb7PG7kj4IhQAA",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "Nikon AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        "focalLength": "26mm",
        "aperture": "f/4.2",
        "shutterSpeed": "1/4000",
        "iso": 500
      },
      "sizes": {
        "full": {
          "width": 8576,
          "height": 5696,
          "url": "/photos/176/pa3/05/full.avif",
          "bytes": 2135070
        },
        "md": {
          "width": 1200,
          "height": 797,
          "url": "/photos/176/pa3/05/1200.avif",
          "bytes": 41422
        },
        "sm": {
          "width": 640,
          "height": 425,
          "url": "/photos/176/pa3/05/640.avif",
          "bytes": 18424
        }
      }
    },
    "176/pa3/08": {
      "file": "08",
      "path": "176/pa3/08",
      "collection": "176/pa3",
      "title": "",
      "alt": "",
      "aspectRatio": 1.5056179775280898,
      "width": 8576,
      "height": 5696,
      "placeholder": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAACwBACdASogABUAPzmSv1mvKaYjqAgB4CcJYwC+SFafN8MwjJsa+JOzKWBru4CgAP70KKgUjXXte+oBPA9/1ZZQH+f27nh4x0e4y7mv6iW/RvNmxlDv8K8lJ1AdlLRWDXIlQdU5V7b6SyiM3swQgiM7qr9usARqu7klKvWQ4bFB/bf06b75FamkAAA=",
      "exif": {
        "camera": "NIKON CORPORATION NIKON D5000",
        "lens": "Nikon AF-S DX NIKKOR 18-55mm f/3.5-5.6G VR",
        "focalLength": "18mm",
        "aperture": "f/4",
        "shutterSpeed": "1/4000",
        "iso": 320
      },
      "sizes": {
        "full": {
          "width": 8576,
          "height": 5696,
          "url": "/photos/176/pa3/08/full.avif",
          "bytes": 2615195
        },
        "md": {
          "width": 1200,
          "height": 797,
          "url": "/photos/176/pa3/08/1200.avif",
          "bytes": 88286
        },
        "sm": {
          "width": 640,
          "height": 425,
          "url": "/photos/176/pa3/08/640.avif",
          "bytes": 29054
        }
      }
    }
  },
  "totalBytes": 31731038
};
