CREATE TABLE IF NOT EXISTS Paintings (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
    data BLOB NOT NULL,
    author_ip TEXT NOT NULL,
    overwritten BOOLEAN DEFAULT FALSE
);

DROP TABLE IF EXISTS Ratelimits;
CREATE TABLE IF NOT EXISTS Ratelimits (
	key TEXT PRIMARY KEY,
	time INTEGER NOT NULL
);
